/* tslint:disable */
/* eslint-disable */
/**
 * Chatwork API
 * API for interacting with Chatwork services
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Contact
 */
export interface Contact {
    /**
     * 
     * @type {number}
     * @memberof Contact
     */
    accountId?: number;
    /**
     * 
     * @type {number}
     * @memberof Contact
     */
    roomId?: number;
    /**
     * 
     * @type {string}
     * @memberof Contact
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Contact
     */
    chatworkId?: string;
    /**
     * 
     * @type {number}
     * @memberof Contact
     */
    organizationId?: number;
    /**
     * 
     * @type {string}
     * @memberof Contact
     */
    organizationName?: string;
    /**
     * 
     * @type {string}
     * @memberof Contact
     */
    department?: string;
    /**
     * 
     * @type {string}
     * @memberof Contact
     */
    avatarImageUrl?: string;
}

/**
 * Check if a given object implements the Contact interface.
 */
export function instanceOfContact(value: object): value is Contact {
    return true;
}

export function ContactFromJSON(json: any): Contact {
    return ContactFromJSONTyped(json, false);
}

export function ContactFromJSONTyped(json: any, ignoreDiscriminator: boolean): Contact {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['account_id'] == null ? undefined : json['account_id'],
        'roomId': json['room_id'] == null ? undefined : json['room_id'],
        'name': json['name'] == null ? undefined : json['name'],
        'chatworkId': json['chatwork_id'] == null ? undefined : json['chatwork_id'],
        'organizationId': json['organization_id'] == null ? undefined : json['organization_id'],
        'organizationName': json['organization_name'] == null ? undefined : json['organization_name'],
        'department': json['department'] == null ? undefined : json['department'],
        'avatarImageUrl': json['avatar_image_url'] == null ? undefined : json['avatar_image_url'],
    };
}

  export function ContactToJSON(json: any): Contact {
      return ContactToJSONTyped(json, false);
  }

  export function ContactToJSONTyped(value?: Contact | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'account_id': value['accountId'],
        'room_id': value['roomId'],
        'name': value['name'],
        'chatwork_id': value['chatworkId'],
        'organization_id': value['organizationId'],
        'organization_name': value['organizationName'],
        'department': value['department'],
        'avatar_image_url': value['avatarImageUrl'],
    };
}

