/* tslint:disable */
/* eslint-disable */
/**
 * Chatwork API
 * API for interacting with Chatwork services
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MyStatus
 */
export interface MyStatus {
    /**
     * 
     * @type {number}
     * @memberof MyStatus
     */
    unreadRoomNum?: number;
    /**
     * 
     * @type {number}
     * @memberof MyStatus
     */
    mentionRoomNum?: number;
    /**
     * 
     * @type {number}
     * @memberof MyStatus
     */
    mytaskRoomNum?: number;
    /**
     * 
     * @type {number}
     * @memberof MyStatus
     */
    unreadNum?: number;
    /**
     * 
     * @type {number}
     * @memberof MyStatus
     */
    mentionNum?: number;
    /**
     * 
     * @type {number}
     * @memberof MyStatus
     */
    mytaskNum?: number;
}

/**
 * Check if a given object implements the MyStatus interface.
 */
export function instanceOfMyStatus(value: object): value is MyStatus {
    return true;
}

export function MyStatusFromJSON(json: any): MyStatus {
    return MyStatusFromJSONTyped(json, false);
}

export function MyStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): MyStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'unreadRoomNum': json['unread_room_num'] == null ? undefined : json['unread_room_num'],
        'mentionRoomNum': json['mention_room_num'] == null ? undefined : json['mention_room_num'],
        'mytaskRoomNum': json['mytask_room_num'] == null ? undefined : json['mytask_room_num'],
        'unreadNum': json['unread_num'] == null ? undefined : json['unread_num'],
        'mentionNum': json['mention_num'] == null ? undefined : json['mention_num'],
        'mytaskNum': json['mytask_num'] == null ? undefined : json['mytask_num'],
    };
}

  export function MyStatusToJSON(json: any): MyStatus {
      return MyStatusToJSONTyped(json, false);
  }

  export function MyStatusToJSONTyped(value?: MyStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'unread_room_num': value['unreadRoomNum'],
        'mention_room_num': value['mentionRoomNum'],
        'mytask_room_num': value['mytaskRoomNum'],
        'unread_num': value['unreadNum'],
        'mention_num': value['mentionNum'],
        'mytask_num': value['mytaskNum'],
    };
}

