/* tslint:disable */
/* eslint-disable */
/**
 * Chatwork API
 * API for interacting with Chatwork services
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RoomsRoomIdMessagesPost200Response
 */
export interface RoomsRoomIdMessagesPost200Response {
    /**
     * 
     * @type {string}
     * @memberof RoomsRoomIdMessagesPost200Response
     */
    messageId?: string;
}

/**
 * Check if a given object implements the RoomsRoomIdMessagesPost200Response interface.
 */
export function instanceOfRoomsRoomIdMessagesPost200Response(value: object): value is RoomsRoomIdMessagesPost200Response {
    return true;
}

export function RoomsRoomIdMessagesPost200ResponseFromJSON(json: any): RoomsRoomIdMessagesPost200Response {
    return RoomsRoomIdMessagesPost200ResponseFromJSONTyped(json, false);
}

export function RoomsRoomIdMessagesPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoomsRoomIdMessagesPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'messageId': json['message_id'] == null ? undefined : json['message_id'],
    };
}

  export function RoomsRoomIdMessagesPost200ResponseToJSON(json: any): RoomsRoomIdMessagesPost200Response {
      return RoomsRoomIdMessagesPost200ResponseToJSONTyped(json, false);
  }

  export function RoomsRoomIdMessagesPost200ResponseToJSONTyped(value?: RoomsRoomIdMessagesPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message_id': value['messageId'],
    };
}

