/* tslint:disable */
/* eslint-disable */
/**
 * Chatwork API
 * API for interacting with Chatwork services
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RoomsRoomIdTasksPost200Response
 */
export interface RoomsRoomIdTasksPost200Response {
    /**
     * 
     * @type {Array<number>}
     * @memberof RoomsRoomIdTasksPost200Response
     */
    taskIds?: Array<number>;
}

/**
 * Check if a given object implements the RoomsRoomIdTasksPost200Response interface.
 */
export function instanceOfRoomsRoomIdTasksPost200Response(value: object): value is RoomsRoomIdTasksPost200Response {
    return true;
}

export function RoomsRoomIdTasksPost200ResponseFromJSON(json: any): RoomsRoomIdTasksPost200Response {
    return RoomsRoomIdTasksPost200ResponseFromJSONTyped(json, false);
}

export function RoomsRoomIdTasksPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoomsRoomIdTasksPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'taskIds': json['task_ids'] == null ? undefined : json['task_ids'],
    };
}

  export function RoomsRoomIdTasksPost200ResponseToJSON(json: any): RoomsRoomIdTasksPost200Response {
      return RoomsRoomIdTasksPost200ResponseToJSONTyped(json, false);
  }

  export function RoomsRoomIdTasksPost200ResponseToJSONTyped(value?: RoomsRoomIdTasksPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'task_ids': value['taskIds'],
    };
}

