import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { authApi } from "@/lib/chatwork";
import { getCurrentSession } from "@/lib/cookies";
import { redirect } from "next/navigation";
import { Panel, PanelGroup } from "react-resizable-panels";
import ResizableLayout from "@/components/ResizableLayout";
import { cookies } from "next/headers";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { user } = await getCurrentSession();
  if (!user) {
    redirect("/login/chatwork");
  }

  const rooms = await authApi.roomsGet();

  const cookieStore = await cookies();
  const layout = cookieStore.get("react-resizable-panels:layout");

  let defaultLayout;
  if (layout) {
    defaultLayout = JSON.parse(layout.value);
  }

  return (
    <html lang="en" className="w-full h-full">
      <body
        className={`antialiased w-full h-full`}
      >
        <section className="flex flex-col max-h-full h-full">
          <nav className="text-white w-full justify-between bg-[#221127]">
            <div className="mx-4 my-4">Chatwork</div>
          </nav>
          <ResizableLayout defaultLayout={defaultLayout} rooms={rooms} children={children} />
        </section>
      </body>
    </html>
  );
}
