import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { authApi } from "@/lib/chatwork";
import { getCurrentSession } from "@/lib/cookies";
import { redirect } from "next/navigation";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { user } = await getCurrentSession();
  if (!user) {
    redirect("/login/chatwork");
  }

  let rooms = [];

  try {
    const me = await authApi.meGet();
    rooms = await authApi.roomsGet();
  } catch (error) {
    console.error(error);
  }

  return (
    <html lang="en" className="w-full h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-full h-full`}
      >
        <section className="flex flex-col">
          <section className=""></section>
          <nav className="h-full">
            {rooms.map((room) => (
              <div key={room.roomId}>{room.name}</div>
            ))}
          </nav>
          {children}
        </section>
      </body>
    </html>
  );
}
